"""empty message

Revision ID: f02409a0d9db
Revises: 895d317f8e6e
Create Date: 2020-09-11 23:29:16.946996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f02409a0d9db'
down_revision = '895d317f8e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_delete', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_delete')
    # ### end Alembic commands ###
